"""adiconando novo relacioanamento

Revision ID: 0ca06d5b4e5a
Revises: cb60caee7cab
Create Date: 2025-11-30 16:21:02.490146

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ca06d5b4e5a'
down_revision: Union[str, Sequence[str], None] = 'cb60caee7cab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'itens_pedido', 'pedidos', ['pedido_id'], ['id'])
    op.create_foreign_key(None, 'pedidos', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_constraint(None, 'itens_pedido', type_='foreignkey')
    # ### end Alembic commands ###
