"""adiconando novo relacioanamento

Revision ID: 223b34272c39
Revises: b1d8e4ae8cc9
Create Date: 2025-11-30 17:12:45.087229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '223b34272c39'
down_revision: Union[str, Sequence[str], None] = 'b1d8e4ae8cc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'itens_pedido', 'pedidos', ['pedido_id'], ['id'])
    op.create_foreign_key(None, 'pedidos', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_constraint(None, 'itens_pedido', type_='foreignkey')
    # ### end Alembic commands ###
