"""adicionar itens no pedido

Revision ID: 3d5d90a5ca3b
Revises: 3efffe6c88cd
Create Date: 2025-11-30 15:33:06.874923

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d5d90a5ca3b'
down_revision: Union[str, Sequence[str], None] = '3efffe6c88cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'itens_pedido', 'pedidos', ['pedido_id'], ['id'])
    op.create_foreign_key(None, 'pedidos', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pedidos', type_='foreignkey')
    op.drop_constraint(None, 'itens_pedido', type_='foreignkey')
    # ### end Alembic commands ###
